tasks:
  - init: pyenv install 3.9.10
    command: pyenv install 3.9.10
    
  - init: pip install -r requirements.txt
    command: pip install -r requirements.txt

ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: false